name: Keep Supabase Alive

on:
  schedule:
    - cron: '0 0 */3 * *'  # ทุก 3 วัน
  workflow_dispatch:        # กด run เองได้

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Supabase
        run: |
          curl -s \
            "https://goufoedhjkvhbjahzfvq.supabase.co/rest/v1/users?select=id&limit=1" \
            -H "apikey: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdvdWZvZWRoamt2aGJqYWh6ZnZxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzg0NjgyMTAsImV4cCI6MjA5NDA0NDIxMH0.LoCQv2ThFNwSunYvTmUjUXx99QWVEmAwThxiwXptx8s" \
            -H "Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdvdWZvZWRoamt2aGJqYWh6ZnZxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzg0NjgyMTAsImV4cCI6MjA5NDA0NDIxMH0.LoCQv2ThFNwSunYvTmUjUXx99QWVEmAwThxiwXptx8s" \
            && echo "Supabase is alive!"
